//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int Id { get; set; }
        public string model_name { get; set; }
        public string model_description { get; set; }
        public Nullable<decimal> model_price { get; set; }
        public byte[] model_image { get; set; }
        public Nullable<bool> is_endorsed { get; set; }
        public string publisher_name { get; set; }
    }
}
